


# Permalinks
permalink:        pretty

# Setup
title:            Holy Cross Manuscripts Hackathon
tagline:          'February 2, 2019'
description:      'One-day collaborative hackathon to produce a digital diplomatic edition of an 11th-century manuscript of the Aratea of Germanicus Caesar (Bern,	Burgerbibliothek,	Codex 88).'


baseurl: '/ms-hackathon-2019/'


author:
  name:           'Neel Smith'


links:
  - title:  Preparation
    url:  /preparation
  - title: Schedule
    url:  /schedule
  - title: Images of the manuscript
    url:  /bern88-thumbs
  - title: References for editors
    url:  /references
  - title: Hackathon home page
    url:  /
  - title: HC MID club
    url: http://hcmid.github.io/
    external: true
  - title: Acknowledgments
    url: gratias
